[project]
name = "jirre"
version = "0.1.0"
description = "Jirre is a simple local first ticketting system."
readme = "README.md"
license = { file = "LICENSE"}
requires-python = ">=3.13"
dependencies = [
    "rich>=13.9.4",
]

[project.scripts]
jirre = "jirre.main:main"
